### ISSUE TITLE
Update WebdriverIO v8

### ISSUE THREAD

**Issue by olgapuig** [systelab/systelab-components-wdio-test#39]
**Is your feature request related to a problem? Please describe.**
WDIOv8 was released on December'22. https://webdriver.io/blog/2022/12/01/webdriverio-v8-released/

**Describe the solution you'd like**
Update WDIO dependencies from 7.16.x to 8.x.y
@wdio/allure-reporter
@wdio/cli
@wdio/jasmine-framework":
@wdio/local-runner
@wdio/spec-reporter
@wdio/types

**Additional context**
Consider seed-angular to test it

**Comment by joaquimvila** [comment]
Rather than updating the dependencies to an specific v8 version, it would be great to mark them as "peerDependencies", so it's each project that uses this library would inject the specific WDIO version to be used. Then, each "peer-dependency" should only specify a range (i.e greater or equal than 8.0.0 and strictly lower than 9.0.0)

**Comment by jperez1-via** [comment]
Created systelab-components-wdio-test base lib v.2.0.0 for WDIO v8.

However, the lib structure has not been redone to use peerDependencies. Opening a specific issue for this topic.
